name: Publish Nightly Builds
on:
  workflow_run:
    workflows:
      - Build Nightly
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Download artifacts
      uses: dawidd6/action-download-artifact@v2.26.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        run_id: ${{ github.event.workflow_run.id }}
        skip_unpack: true
        path: ./artifacts

    - name: Delete tag and release
      uses: dev-drprasad/delete-tag-and-release@v0.2.1
      with:
        delete_release: true
        tag_name: nightly
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: nightly
        name: Nightly Builds
        prerelease: false
        files: ./artifacts/*
        body: |
          This is an automatic nightly release of Crow Engine.
          Note that Nightly Builds are unstable, and you may experience bugs, crashes, unintended behavior, or unfinished products.

          Please report any bugs to the [Issues](https://github.com/EyeDaleHim/Crow-Engine/issues) tab, or report them in the [Discord Server](https://discord.gg/QVHSdbzZmy).
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
